//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngressTracker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IngressTracker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutView {
            get {
                return ResourceManager.GetString("AboutView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This project is not officially affiliated with Ingress or Niantic Labs at Google..
        /// </summary>
        public static string Affiliation {
            get {
                return ResourceManager.GetString("Affiliation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent.
        /// </summary>
        public static string Agent {
            get {
                return ResourceManager.GetString("Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Name.
        /// </summary>
        public static string AgentName {
            get {
                return ResourceManager.GetString("AgentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A stats tracking app for Windows PCs.
        /// </summary>
        public static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingress Tracker.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awardable Badges.
        /// </summary>
        public static string AwardableBadges {
            get {
                return ResourceManager.GetString("AwardableBadges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge.
        /// </summary>
        public static string Badge {
            get {
                return ResourceManager.GetString("Badge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Awardable.
        /// </summary>
        public static string BadgeAwardable {
            get {
                return ResourceManager.GetString("BadgeAwardable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Badges.
        /// </summary>
        public static string BadgeAwardView {
            get {
                return ResourceManager.GetString("BadgeAwardView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black Level.
        /// </summary>
        public static string BadgeBlack {
            get {
                return ResourceManager.GetString("BadgeBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bronze Level.
        /// </summary>
        public static string BadgeBronze {
            get {
                return ResourceManager.GetString("BadgeBronze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string BadgeDescription {
            get {
                return ResourceManager.GetString("BadgeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold Level.
        /// </summary>
        public static string BadgeGold {
            get {
                return ResourceManager.GetString("BadgeGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge is awardable..
        /// </summary>
        public static string BadgeIsAwardable {
            get {
                return ResourceManager.GetString("BadgeIsAwardable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge Level.
        /// </summary>
        public static string BadgeLevel {
            get {
                return ResourceManager.GetString("BadgeLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge Name.
        /// </summary>
        public static string BadgeName {
            get {
                return ResourceManager.GetString("BadgeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platinum Level.
        /// </summary>
        public static string BadgePlatinum {
            get {
                return ResourceManager.GetString("BadgePlatinum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge Progress.
        /// </summary>
        public static string BadgeProgressView {
            get {
                return ResourceManager.GetString("BadgeProgressView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver Level.
        /// </summary>
        public static string BadgeSilver {
            get {
                return ResourceManager.GetString("BadgeSilver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badges.
        /// </summary>
        public static string BadgeStaticView {
            get {
                return ResourceManager.GetString("BadgeStaticView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linked Statistic.
        /// </summary>
        public static string BadgeStatistic {
            get {
                return ResourceManager.GetString("BadgeStatistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        public static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bronze.
        /// </summary>
        public static string Bronze {
            get {
                return ResourceManager.GetString("Bronze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        public static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string CategoryStaticView {
            get {
                return ResourceManager.GetString("CategoryStaticView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose your Agent Name:.
        /// </summary>
        public static string ChooseAgentName {
            get {
                return ResourceManager.GetString("ChooseAgentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string ConnectButton {
            get {
                return ResourceManager.GetString("ConnectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Agent:.
        /// </summary>
        public static string CurrentAgent {
            get {
                return ResourceManager.GetString("CurrentAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string DataAddRecord {
            get {
                return ResourceManager.GetString("DataAddRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds a new row to the grid on the current screen..
        /// </summary>
        public static string DataAddRecordHelp {
            get {
                return ResourceManager.GetString("DataAddRecordHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current screen does not support adding a new row..
        /// </summary>
        public static string DataAddRecordHelpDisabled {
            get {
                return ResourceManager.GetString("DataAddRecordHelpDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DataDeleteRecord {
            get {
                return ResourceManager.GetString("DataDeleteRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletes the currently selected row on the grid on the current screen..
        /// </summary>
        public static string DataDeleteRecordHelp {
            get {
                return ResourceManager.GetString("DataDeleteRecordHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current screen does not support deleting rows..
        /// </summary>
        public static string DataDeleteRecordHelpDisabled {
            get {
                return ResourceManager.GetString("DataDeleteRecordHelpDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string DataRefreshRecord {
            get {
                return ResourceManager.GetString("DataRefreshRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshes the data on the current screen from the database, discarding any unsaved changes that have been made.
        /// </summary>
        public static string DataRefreshRecordHelp {
            get {
                return ResourceManager.GetString("DataRefreshRecordHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current screen does not support refreshing the data from the database..
        /// </summary>
        public static string DataRefreshRecordHelpDisabled {
            get {
                return ResourceManager.GetString("DataRefreshRecordHelpDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string DataSaveRecords {
            get {
                return ResourceManager.GetString("DataSaveRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves the data on the current screen..
        /// </summary>
        public static string DataSaveRecordsHelp {
            get {
                return ResourceManager.GetString("DataSaveRecordsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current screen does not support saving..
        /// </summary>
        public static string DataSaveRecordsHelpDisabled {
            get {
                return ResourceManager.GetString("DataSaveRecordsHelpDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string DataToolsActions {
            get {
                return ResourceManager.GetString("DataToolsActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string DataToolsContextualRibbonTab {
            get {
                return ResourceManager.GetString("DataToolsContextualRibbonTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Tools.
        /// </summary>
        public static string DataToolsRibbonTab {
            get {
                return ResourceManager.GetString("DataToolsRibbonTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string DbPassword {
            get {
                return ResourceManager.GetString("DbPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database username.
        /// </summary>
        public static string DbUserName {
            get {
                return ResourceManager.GetString("DbUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Order.
        /// </summary>
        public static string DisplayOrder {
            get {
                return ResourceManager.GetString("DisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earnable Badges.
        /// </summary>
        public static string EarnableBadges {
            get {
                return ResourceManager.GetString("EarnableBadges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Stats.
        /// </summary>
        public static string EnterStatsView {
            get {
                return ResourceManager.GetString("EnterStatsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enlightened.
        /// </summary>
        public static string FactionEnlightened {
            get {
                return ResourceManager.GetString("FactionEnlightened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resistance.
        /// </summary>
        public static string FactionResistance {
            get {
                return ResourceManager.GetString("FactionResistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold.
        /// </summary>
        public static string Gold {
            get {
                return ResourceManager.GetString("Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Data.
        /// </summary>
        public static string ImportDataView {
            get {
                return ResourceManager.GetString("ImportDataView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please map the statistic descriptions to the ones defined in this app:.
        /// </summary>
        public static string ImportMapStatistics {
            get {
                return ResourceManager.GetString("ImportMapStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a CSV file to import:.
        /// </summary>
        public static string ImportSelectFile {
            get {
                return ResourceManager.GetString("ImportSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is AP statistic?.
        /// </summary>
        public static string IsAP {
            get {
                return ResourceManager.GetString("IsAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Points.
        /// </summary>
        public static string LevelAP {
            get {
                return ResourceManager.GetString("LevelAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black Badges Required.
        /// </summary>
        public static string LevelBlacks {
            get {
                return ResourceManager.GetString("LevelBlacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold Badges Required.
        /// </summary>
        public static string LevelGolds {
            get {
                return ResourceManager.GetString("LevelGolds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level #.
        /// </summary>
        public static string LevelNumber {
            get {
                return ResourceManager.GetString("LevelNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platinum Badges Required.
        /// </summary>
        public static string LevelPlatinums {
            get {
                return ResourceManager.GetString("LevelPlatinums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Progress.
        /// </summary>
        public static string LevelProgressView {
            get {
                return ResourceManager.GetString("LevelProgressView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver Badges Required.
        /// </summary>
        public static string LevelSilvers {
            get {
                return ResourceManager.GetString("LevelSilvers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levels.
        /// </summary>
        public static string LevelStaticView {
            get {
                return ResourceManager.GetString("LevelStaticView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apache License
        ///                           Version 2.0, January 2004
        ///                        http://www.apache.org/licenses/
        ///
        ///   TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION
        ///
        ///   1. Definitions.
        ///
        ///      &quot;License&quot; shall mean the terms and conditions for use, reproduction,
        ///      and distribution as defined by Sections 1 through 9 of this document.
        ///
        ///      &quot;Licensor&quot; shall mean the copyright owner or entity authorized by
        ///      the copyright owner that is granting the License.
        ///
        ///      &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LicApache2 {
            get {
                return ResourceManager.GetString("LicApache2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (c) {0}, {1}
        ///All rights reserved.
        ///
        ///Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
        ///
        ///  * Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
        ///  * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LicBSD {
            get {
                return ResourceManager.GetString("LicBSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licence Information.
        /// </summary>
        public static string LicenceInfo {
            get {
                return ResourceManager.GetString("LicenceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GNU LESSER GENERAL PUBLIC LICENSE
        ///                     Version 2.1, February 1999
        ///
        ///       Copyright (C) 1991, 1999 Free Software Foundation, Inc.
        ///       59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
        ///
        ///     Everyone is permitted to copy and distribute verbatim copies
        ///       of this license document, but changing it is not allowed.
        ///
        ///[This is the first released version of the Lesser GPL.  It also counts
        /// as the successor of the GNU Library Public License, version 2, hence
        /// the version numbe [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LicLGPL2 {
            get {
                return ResourceManager.GetString("LicLGPL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (c) {0} {1}
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the following conditions:
        ///
        ///The above copyright notice and this permission [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LicMIT {
            get {
                return ResourceManager.GetString("LicMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Public License (Ms-PL)
        ///
        ///This license governs use of the accompanying software. If you use the software, you accept this license. If you do not accept the license, do not use the software.
        ///
        ///1. Definitions
        ///
        ///The terms &quot;reproduce,&quot; &quot;reproduction,&quot; &quot;derivative works,&quot; and &quot;distribution&quot; have the same meaning here as under U.S. copyright law.
        ///
        ///A &quot;contribution&quot; is the original software, or any additions or changes to the software.
        ///
        ///A &quot;contributor&quot; is any person that distributes its contribution [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LicMSPL {
            get {
                return ResourceManager.GetString("LicMSPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is in the Public Domain..
        /// </summary>
        public static string LicPD {
            get {
                return ResourceManager.GetString("LicPD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked.
        /// </summary>
        public static string Locked {
            get {
                return ResourceManager.GetString("Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginView {
            get {
                return ResourceManager.GetString("LoginView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all stats are specified..
        /// </summary>
        public static string NotAllStatsSpecified {
            get {
                return ResourceManager.GetString("NotAllStatsSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platinum.
        /// </summary>
        public static string Platinum {
            get {
                return ResourceManager.GetString("Platinum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw Statistic Values.
        /// </summary>
        public static string RawValuesView {
            get {
                return ResourceManager.GetString("RawValuesView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS `user` (
        ///  `id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
        ///  `agentname` VARCHAR NOT NULL,
        ///  `faction` VARCHAR NOT NULL,
        ///  `staticadmin` INTEGER NOT NULL DEFAULT &apos;0&apos;
        /// );.
        /// </summary>
        public static string SchemaUpgrade0To1a {
            get {
                return ResourceManager.GetString("SchemaUpgrade0To1a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS `category` (
        ///  `id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
        ///  `name` VARCHAR NOT NULL,
        ///  `displayorder` INTEGER NULL);.
        /// </summary>
        public static string SchemaUpgrade0To1b {
            get {
                return ResourceManager.GetString("SchemaUpgrade0To1b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS `stat` (
        ///  `id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
        ///  `description` VARCHAR NOT NULL,
        ///  `unit` VARCHAR NULL,
        ///  `category` INT NOT NULL,
        ///  `predictability` INTEGER NOT NULL,
        ///  `displayorder` INTEGER NULL DEFAULT NULL,
        ///  `ap` INTEGER NOT NULL DEFAULT 0,
        ///    FOREIGN KEY (`category`)
        ///    REFERENCES `category` (`id`))
        ///;.
        /// </summary>
        public static string SchemaUpgrade0To1c {
            get {
                return ResourceManager.GetString("SchemaUpgrade0To1c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS `badge` (
        ///  `id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
        ///  `name` VARCHAR NOT NULL,
        ///  `stat` INTEGER NULL,
        ///  `bronze` INTEGER NULL,
        ///  `silver` INTEGER NULL,
        ///  `gold` INTEGER NULL,
        ///  `platinum` INTEGER NULL,
        ///  `black` INTEGER NULL,
        ///  `awardable` INTEGER NOT NULL,
        ///  `description` VARCHAR(255) NULL,
        ///    FOREIGN KEY (`stat`)
        ///    REFERENCES `stat` (`id`)
        ///    ON DELETE RESTRICT
        ///    ON UPDATE RESTRICT)
        ///;.
        /// </summary>
        public static string SchemaUpgrade0To1d {
            get {
                return ResourceManager.GetString("SchemaUpgrade0To1d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS `value` (
        ///  `id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
        ///  `user` INTEGER NOT NULL,
        ///  `stat` INTEGER NOT NULL,
        ///  `value` INTEGER NOT NULL,
        ///  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        ///    FOREIGN KEY (`stat`)
        ///    REFERENCES `stat` (`id`)
        ///    ON DELETE RESTRICT
        ///    ON UPDATE RESTRICT,
        ///    FOREIGN KEY (`user`)
        ///    REFERENCES `user` (`id`)
        ///    ON DELETE RESTRICT
        ///    ON UPDATE RESTRICT)
        ///;.
        /// </summary>
        public static string SchemaUpgrade0To1e {
            get {
                return ResourceManager.GetString("SchemaUpgrade0To1e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS `level` (
        ///  `id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
        ///  `level` INTEGER NOT NULL,
        ///  `ap` INTEGER NOT NULL,
        ///  `silver` INTEGER NOT NULL,
        ///  `gold` INTEGER NOT NULL,
        ///  `platinum` INTEGER NOT NULL,
        ///  `black` INTEGER NOT NULL
        ///)
        ///;.
        /// </summary>
        public static string SchemaUpgrade0To1f {
            get {
                return ResourceManager.GetString("SchemaUpgrade0To1f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS `badgeaward` (
        ///  `id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
        ///  `user` INTEGER NOT NULL,
        ///  `badge` INTEGER NOT NULL,
        ///  `level` VARCHAR(1) NOT NULL,
        ///    FOREIGN KEY (`user`)
        ///    REFERENCES `user` (`id`)
        ///    ON DELETE NO ACTION
        ///    ON UPDATE NO ACTION,
        ///    FOREIGN KEY (`badge`)
        ///    REFERENCES `badge` (`id`)
        ///    ON DELETE NO ACTION
        ///    ON UPDATE NO ACTION)
        ///;.
        /// </summary>
        public static string SchemaUpgrade0To1g {
            get {
                return ResourceManager.GetString("SchemaUpgrade0To1g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO user VALUES (1, &apos;defaultuser&apos;, &apos;ENL&apos;, 1);
        ///INSERT INTO category VALUES (1,&apos;AP&apos;,1);
        ///INSERT INTO category VALUES (2,&apos;Discovery&apos;,2);
        ///INSERT INTO category VALUES (3,&apos;Health&apos;,3);
        ///INSERT INTO category VALUES (4,&apos;Building&apos;,4);
        ///INSERT INTO category VALUES (5,&apos;Combat&apos;,5);
        ///INSERT INTO category VALUES (6,&apos;Defence&apos;,6);
        ///INSERT INTO category VALUES (7,&apos;Missions&apos;,7);
        ///INSERT INTO category VALUES (8,&apos;Resource Gathering&apos;,8);
        ///INSERT INTO category VALUES (9,&apos;(unknown)&apos;,9999);
        ///INSERT INTO level VALUES (1,1, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SchemaUpgrade0To1h {
            get {
                return ResourceManager.GetString("SchemaUpgrade0To1h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screens.
        /// </summary>
        public static string Screens {
            get {
                return ResourceManager.GetString("Screens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver.
        /// </summary>
        public static string Silver {
            get {
                return ResourceManager.GetString("Silver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static Data.
        /// </summary>
        public static string StaticData {
            get {
                return ResourceManager.GetString("StaticData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistic.
        /// </summary>
        public static string Statistic {
            get {
                return ResourceManager.GetString("Statistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string StatisticCategory {
            get {
                return ResourceManager.GetString("StatisticCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string StatisticDescription {
            get {
                return ResourceManager.GetString("StatisticDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predictable?.
        /// </summary>
        public static string StatisticPredictable {
            get {
                return ResourceManager.GetString("StatisticPredictable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string StatisticUnit {
            get {
                return ResourceManager.GetString("StatisticUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string StatStaticView {
            get {
                return ResourceManager.GetString("StatStaticView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        public static string Timestamp {
            get {
                return ResourceManager.GetString("Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingress, the Ingress logo, and graphics relating to Ingress are Copyright (c) Google Inc, and may also be registered trademarks..
        /// </summary>
        public static string Trademarks {
            get {
                return ResourceManager.GetString("Trademarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t saved your changes on this screen! Continuing will discard any changes you have made. Are you sure you wish to continue?.
        /// </summary>
        public static string UnsavedChanges {
            get {
                return ResourceManager.GetString("UnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved changes!.
        /// </summary>
        public static string UnsavedChangesTitle {
            get {
                return ResourceManager.GetString("UnsavedChangesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to all agent profiles.
        /// </summary>
        public static string UserAccessToAllUsers {
            get {
                return ResourceManager.GetString("UserAccessToAllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faction.
        /// </summary>
        public static string UserFaction {
            get {
                return ResourceManager.GetString("UserFaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string UserOverviewView {
            get {
                return ResourceManager.GetString("UserOverviewView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static Data Administrator.
        /// </summary>
        public static string UserStaticDataAdmin {
            get {
                return ResourceManager.GetString("UserStaticDataAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string UserStaticView {
            get {
                return ResourceManager.GetString("UserStaticView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.
        /// </summary>
        public static string WindowListRibbonTab {
            get {
                return ResourceManager.GetString("WindowListRibbonTab", resourceCulture);
            }
        }
    }
}
