//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngressTracker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IngressTracker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent.
        /// </summary>
        public static string Agent {
            get {
                return ResourceManager.GetString("Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Name.
        /// </summary>
        public static string AgentName {
            get {
                return ResourceManager.GetString("AgentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingress Tracker.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge.
        /// </summary>
        public static string Badge {
            get {
                return ResourceManager.GetString("Badge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Awardable.
        /// </summary>
        public static string BadgeAwardable {
            get {
                return ResourceManager.GetString("BadgeAwardable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Badges.
        /// </summary>
        public static string BadgeAwardView {
            get {
                return ResourceManager.GetString("BadgeAwardView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black Level.
        /// </summary>
        public static string BadgeBlack {
            get {
                return ResourceManager.GetString("BadgeBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bronze Level.
        /// </summary>
        public static string BadgeBronze {
            get {
                return ResourceManager.GetString("BadgeBronze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold Level.
        /// </summary>
        public static string BadgeGold {
            get {
                return ResourceManager.GetString("BadgeGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge Level.
        /// </summary>
        public static string BadgeLevel {
            get {
                return ResourceManager.GetString("BadgeLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge Name.
        /// </summary>
        public static string BadgeName {
            get {
                return ResourceManager.GetString("BadgeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platinum Level.
        /// </summary>
        public static string BadgePlatinum {
            get {
                return ResourceManager.GetString("BadgePlatinum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver Level.
        /// </summary>
        public static string BadgeSilver {
            get {
                return ResourceManager.GetString("BadgeSilver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badges.
        /// </summary>
        public static string BadgeStaticView {
            get {
                return ResourceManager.GetString("BadgeStaticView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linked Statistic.
        /// </summary>
        public static string BadgeStatistic {
            get {
                return ResourceManager.GetString("BadgeStatistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        public static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bronze.
        /// </summary>
        public static string Bronze {
            get {
                return ResourceManager.GetString("Bronze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        public static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string CategoryStaticView {
            get {
                return ResourceManager.GetString("CategoryStaticView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose your Agent Name:.
        /// </summary>
        public static string ChooseAgentName {
            get {
                return ResourceManager.GetString("ChooseAgentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string ConnectButton {
            get {
                return ResourceManager.GetString("ConnectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Agent:.
        /// </summary>
        public static string CurrentAgent {
            get {
                return ResourceManager.GetString("CurrentAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string DataAddRecord {
            get {
                return ResourceManager.GetString("DataAddRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DataDeleteRecord {
            get {
                return ResourceManager.GetString("DataDeleteRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string DataRefreshRecord {
            get {
                return ResourceManager.GetString("DataRefreshRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string DataSaveRecords {
            get {
                return ResourceManager.GetString("DataSaveRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string DataToolsActions {
            get {
                return ResourceManager.GetString("DataToolsActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string DataToolsContextualRibbonTab {
            get {
                return ResourceManager.GetString("DataToolsContextualRibbonTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Tools.
        /// </summary>
        public static string DataToolsRibbonTab {
            get {
                return ResourceManager.GetString("DataToolsRibbonTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string DbPassword {
            get {
                return ResourceManager.GetString("DbPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database username.
        /// </summary>
        public static string DbUserName {
            get {
                return ResourceManager.GetString("DbUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Order.
        /// </summary>
        public static string DisplayOrder {
            get {
                return ResourceManager.GetString("DisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enlightened.
        /// </summary>
        public static string FactionEnlightened {
            get {
                return ResourceManager.GetString("FactionEnlightened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resistance.
        /// </summary>
        public static string FactionResistance {
            get {
                return ResourceManager.GetString("FactionResistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold.
        /// </summary>
        public static string Gold {
            get {
                return ResourceManager.GetString("Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Points.
        /// </summary>
        public static string LevelAP {
            get {
                return ResourceManager.GetString("LevelAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black Badges Required.
        /// </summary>
        public static string LevelBlacks {
            get {
                return ResourceManager.GetString("LevelBlacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold Badges Required.
        /// </summary>
        public static string LevelGolds {
            get {
                return ResourceManager.GetString("LevelGolds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level #.
        /// </summary>
        public static string LevelNumber {
            get {
                return ResourceManager.GetString("LevelNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platinum Badges Required.
        /// </summary>
        public static string LevelPlatinums {
            get {
                return ResourceManager.GetString("LevelPlatinums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver Badges Required.
        /// </summary>
        public static string LevelSilvers {
            get {
                return ResourceManager.GetString("LevelSilvers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levels.
        /// </summary>
        public static string LevelStaticView {
            get {
                return ResourceManager.GetString("LevelStaticView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginView {
            get {
                return ResourceManager.GetString("LoginView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platinum.
        /// </summary>
        public static string Platinum {
            get {
                return ResourceManager.GetString("Platinum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw Statistic Values.
        /// </summary>
        public static string RawValuesView {
            get {
                return ResourceManager.GetString("RawValuesView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screens.
        /// </summary>
        public static string Screens {
            get {
                return ResourceManager.GetString("Screens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver.
        /// </summary>
        public static string Silver {
            get {
                return ResourceManager.GetString("Silver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static Data.
        /// </summary>
        public static string StaticData {
            get {
                return ResourceManager.GetString("StaticData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistic.
        /// </summary>
        public static string Statistic {
            get {
                return ResourceManager.GetString("Statistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string StatisticCategory {
            get {
                return ResourceManager.GetString("StatisticCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string StatisticDescription {
            get {
                return ResourceManager.GetString("StatisticDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predictable?.
        /// </summary>
        public static string StatisticPredictable {
            get {
                return ResourceManager.GetString("StatisticPredictable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string StatisticUnit {
            get {
                return ResourceManager.GetString("StatisticUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string StatStaticView {
            get {
                return ResourceManager.GetString("StatStaticView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        public static string Timestamp {
            get {
                return ResourceManager.GetString("Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t saved your changes on this screen! Continuing will discard any changes you have made. Are you sure you wish to continue?.
        /// </summary>
        public static string UnsavedChanges {
            get {
                return ResourceManager.GetString("UnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved changes!.
        /// </summary>
        public static string UnsavedChangesTitle {
            get {
                return ResourceManager.GetString("UnsavedChangesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to all agent profiles.
        /// </summary>
        public static string UserAccessToAllUsers {
            get {
                return ResourceManager.GetString("UserAccessToAllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faction.
        /// </summary>
        public static string UserFaction {
            get {
                return ResourceManager.GetString("UserFaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string UserOverviewView {
            get {
                return ResourceManager.GetString("UserOverviewView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static Data Administrator.
        /// </summary>
        public static string UserStaticDataAdmin {
            get {
                return ResourceManager.GetString("UserStaticDataAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string UserStaticView {
            get {
                return ResourceManager.GetString("UserStaticView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.
        /// </summary>
        public static string WindowListRibbonTab {
            get {
                return ResourceManager.GetString("WindowListRibbonTab", resourceCulture);
            }
        }
    }
}
